sudo: required

services:
  - docker

before_install:
  - docker build --rm -t nginx-length-hiding-filter-module-test -f Dockerfile.test .

script:
  - docker run --rm nginx-length-hiding-filter-module-test